import { NextResponse, NextRequest } from "next/server";

export async function GET() {
  return NextResponse.json({ message: "TrafficFlow API v21.0 - Active" });
}

// Fallback content generator
function generateFallbackContent(topic: string, type: string, tone: string): string {
  const templates: Record<string, (t: string, tone: string) => string> = {
    blog: (t, tone) => `# ${t}: A Comprehensive Guide

${tone === 'professional' ? 'In this comprehensive article, we explore the key aspects of' : tone === 'casual' ? "Let's dive into" : `Discover everything you need to know about`} ${t}.

## Introduction

Understanding ${t} is essential for anyone looking to improve their digital presence. This guide will walk you through the fundamentals and advanced strategies that will help you achieve remarkable results in today's competitive landscape.

## Why ${t} Matters

The digital landscape is constantly evolving, and staying ahead requires a deep understanding of ${t}. Businesses and individuals who master these concepts consistently outperform their competitors and achieve sustainable growth.

### Key Statistics

- 93% of online experiences begin with search engines
- 75% of users never scroll past the first page of search results
- Companies that blog receive 97% more links to their website
- Content marketing costs 62% less than traditional marketing

## Core Strategies for Success

### 1. Foundation Building
Start with a solid understanding of your target audience and their needs. Research thoroughly and create content that addresses real pain points.

### 2. Implementation Excellence
Execute your strategies with precision and consistency. Monitor results and adjust your approach based on data-driven insights.

### 3. Continuous Optimization
Never stop improving. Use analytics to identify opportunities and refine your tactics for better performance over time.

## Best Practices

When implementing ${t} strategies, consider these essential tips:

- **Research First**: Understand your audience and competition before taking action
- **Quality Over Quantity**: Focus on creating valuable, comprehensive content
- **Data-Driven Decisions**: Let analytics guide your optimization efforts
- **Consistency**: Maintain a regular schedule for maximum impact

## Common Mistakes to Avoid

1. Neglecting mobile optimization
2. Ignoring user experience signals
3. Focusing solely on keywords rather than user intent
4. Underestimating the power of internal linking

## Advanced Techniques

For those ready to take their ${t} efforts to the next level, consider:

- Implementing schema markup for rich snippets
- Creating comprehensive pillar content
- Building a strategic internal linking structure
- Leveraging AI and automation tools

## Measuring Success

Track these key metrics to evaluate your ${t} effectiveness:

- Organic traffic growth
- Search ranking improvements
- Engagement metrics (time on page, bounce rate)
- Conversion rates
- Backlink acquisition

## Conclusion

${t} remains a crucial element of any successful digital strategy. By following the guidelines in this article and staying committed to continuous improvement, you'll be well-positioned to achieve your goals and maintain a competitive edge.

---

*This content was generated by TrafficFlow AI Content Generator*`,

    product: (t, tone) => `**${t}** - Premium Quality Solution

${tone === 'professional' ? 'Elevate your business with our' : 'Discover our'} exceptional ${t} solution, designed to meet your specific needs and exceed your expectations.

### Features:
- ✓ Premium quality and reliability
- ✓ Expert-backed methodology  
- ✓ Proven results across industries
- ✓ Dedicated support team
- ✓ Regular updates and improvements

### Why Choose Us?
Our ${t} solution stands out for its quality, effectiveness, and customer satisfaction. We've helped hundreds of businesses achieve their goals through our innovative approach and commitment to excellence.

**Key Benefits:**
- Increase efficiency by up to 40%
- Reduce operational costs
- Improve customer satisfaction
- Scale your operations seamlessly

### What Our Customers Say:
"This solution transformed our business operations completely." - Satisfied Customer

### Pricing:
Contact us for custom pricing tailored to your needs. We offer flexible plans to suit businesses of all sizes.

*Order now and transform your business with ${t}!*`,

    landing: (t, tone) => `# Transform Your Business with ${t}

${tone === 'professional' ? 'Welcome to the future of' : 'Ready to master'} ${t}? You're in the right place.

## What We Offer

✓ Expert guidance on ${t}
✓ Proven strategies that deliver results
✓ Personalized approach for your business
✓ Ongoing support and optimization

## Our Process

### 1. Discovery
We analyze your current situation, identify opportunities, and understand your goals.

### 2. Strategy
We develop a custom ${t} plan tailored to your specific needs and objectives.

### 3. Implementation
We execute with precision, keeping you informed every step of the way.

### 4. Results
You see measurable improvements in your key performance indicators.

## Why Choose Us?

- **10+ Years Experience** in ${t} solutions
- **500+ Happy Clients** who achieved their goals
- **24/7 Support** whenever you need assistance
- **Money-Back Guarantee** - your satisfaction is our priority

## Get Started Today

Don't wait to improve your ${t} strategy. Join thousands of successful businesses who have transformed their operations with our help.

**[Get Started] [Learn More] [Contact Us]**`,

    meta: (t, tone) => `${t} - Comprehensive Guide & Expert Tips | Your Brand

Discover expert insights on ${t}. Learn best practices, strategies, and tips to improve your results. Free consultation available.`,

    social: (t, tone) => `🚀 ${t} - The Ultimate Guide!

${tone === 'casual' ? "Looking to level up your" : 'Master'} ${t} with our expert tips! 📈

✅ Proven strategies
✅ Easy implementation  
✅ Real results
✅ Step-by-step guidance

Click the link to learn more! 👇

#${t.replace(/\s+/g, '')} #DigitalMarketing #SEO #Growth #Tips #Strategy`
  };

  return templates[type]?.(topic, tone) || templates.blog(topic, tone);
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { action, topic, type, tone } = body;

    if (action === 'generate-content' || topic) {
      // Try AI Content Generation, fallback to template if unavailable
      let content = '';
      let usedAI = false;

      try {
        // Dynamic import to handle potential SDK issues
        const ZAI = (await import('z-ai-web-dev-sdk')).default;
        const zai = await ZAI.create();
        
        const typePrompts: Record<string, string> = {
          blog: 'Write a comprehensive blog post',
          product: 'Write a compelling product description',
          landing: 'Write high-converting landing page copy',
          meta: 'Write a SEO meta description (under 160 characters)',
          social: 'Write an engaging social media post'
        };

        const toneInstructions: Record<string, string> = {
          professional: 'Use a professional, authoritative tone',
          casual: 'Use a casual, friendly tone',
          technical: 'Use a technical, detailed tone',
          friendly: 'Use a warm, approachable tone'
        };

        const prompt = `${typePrompts[type] || typePrompts.blog} about "${topic}". ${toneInstructions[tone] || toneInstructions.professional}. 
          Make it SEO-optimized with relevant keywords naturally integrated.
          Include engaging headings and clear structure.
          Make it valuable and actionable for readers.`;

        const completion = await zai.chat.completions.create({
          messages: [
            {
              role: 'system',
              content: 'You are an expert SEO content writer. Create high-quality, engaging content that ranks well in search engines.'
            },
            {
              role: 'user',
              content: prompt
            }
          ],
          max_tokens: type === 'meta' ? 100 : type === 'social' ? 300 : 1500
        });

        content = completion.choices[0]?.message?.content || '';
        usedAI = true;
      } catch (aiError) {
        // AI generation failed, use fallback
        console.log('AI generation unavailable, using fallback template');
        content = generateFallbackContent(topic, type || 'blog', tone || 'professional');
      }

      // If AI returned empty content, use fallback
      if (!content) {
        content = generateFallbackContent(topic, type || 'blog', tone || 'professional');
      }
      
      return NextResponse.json({ 
        success: true, 
        content,
        type,
        topic,
        generatedAt: new Date().toISOString(),
        method: usedAI ? 'ai' : 'template'
      });
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
  } catch (error: any) {
    console.error('API Error:', error);
    
    // Return fallback content on any error
    try {
      const body = await request.clone().json();
      const { topic, type, tone } = body;
      
      if (topic) {
        return NextResponse.json({ 
          success: true, 
          content: generateFallbackContent(topic, type || 'blog', tone || 'professional'),
          type: type || 'blog',
          topic,
          generatedAt: new Date().toISOString(),
          method: 'template'
        });
      }
    } catch {}
    
    return NextResponse.json({ 
      error: 'Failed to process request',
      message: error.message 
    }, { status: 500 });
  }
}
